name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake
      - name: Configure Project
        run: |
          mkdir -p build
          cd build
          cmake -S .. -B . -DCMAKE_BUILD_TYPE=Release -DUSE_OPENGL=ON
      - name: Build Project
        run: |
          cd build
          make
      - name: Run Test
        run: |
          cd build
          ctest --output-on-failure
